### ISSUE TITLE
[PE-D][Tester D] clashed mocules are allocated automatically

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-T17-3/tp#68]
![image.png](https://raw.githubusercontent.com/sylviahe171/ped/main/files/4c9e651b-3314-4985-ae58-2caa10689477.png)

After fin3701A is set for Friday afternoon, I added CS2113. Though their time clashed, CS2113 is allocated successfully. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: sylviahe171/ped#3

**Comment by AaaaaronC** [comment]
expected behaviour, user set mod on friday, and added a mod with fixed lecture slot on friday
