### ISSUE TITLE
[PE-D][Tester A] Another uncaught exception with allocate

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-T17-3/tp#87]
![image.png](https://raw.githubusercontent.com/ongzhihong/ped/main/files/88a626db-f195-4f38-93ae-77703af4ced3.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: ongzhihong/ped#15

**Comment by AaaaaronC** [comment]
caused by saturday lesson
